name        "digitlab-deploy"
description "Deploy applications to DigitLab way"
maintainer  "AWS OpsWorks"
license     "Apache 2.0"
version     "1.0.0"

depends "dependencies"
depends "scm_helper"
depends "apache2"
depends "mod_php5_apache2"
depends "nginx"
depends "ssh_users"
depends "opsworks_agent_monit"
depends "passenger_apache2"
depends "unicorn"
depends "opsworks_java"
depends "php"
depends "mysql"
depends "opsworks_nodejs"
depends "opsworks_aws_flow_ruby"
depends "supervisord"
depends "deploy"

recipe "digitlab-deploy::php", "Deploy a PHP application"