###
# This is the place to override the mod_php5_apache2 cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "mod_php5_apache2/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the mod_php5_apache2 packages:
#
normal[:mod_php5_apache2][:packages] = [ 'php-common',
                                         'php-cli',
                                         'php-curl',
                                         'php-gd',
                                         'php-intl',
                                         'php-mcrypt',
                                         'php-imap',
                                         'php-mysql' ]