###
# This is the place to override the mod_php5_apache2 cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "mod_php5_apache2/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

normal[:mod_php5_apache2][:packages] = [ 'php5-common',
                                         'php5-cli',
                                         'php5-curl',
                                         'php5-gd',
                                         'php5-intl',
                                         'php5-mcrypt',
                                         'php5-memcache',
                                         'php5-imap',
                                         'php5-mysql',
                                         'php5-mongo']